## File generated by the BNF Converter (bnfc 2.9.5).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : T/Test

# Rules for building the parser.

T/Abs.hs T/Lex.x T/Par.y T/Print.hs T/Test.hs : systemt/T.cf
	bnfc --haskell -d systemt/T.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

T/Test : T/Abs.hs T/Lex.hs T/Par.hs T/Print.hs T/Test.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f T/*.hi T/*.o T/*.log T/*.aux T/*.dvi

distclean : clean
	-rm -f T/Abs.hs T/Abs.hs.bak T/ComposOp.hs T/ComposOp.hs.bak T/Doc.txt T/Doc.txt.bak T/ErrM.hs T/ErrM.hs.bak T/Layout.hs T/Layout.hs.bak T/Lex.x T/Lex.x.bak T/Par.y T/Par.y.bak T/Print.hs T/Print.hs.bak T/Skel.hs T/Skel.hs.bak T/Test.hs T/Test.hs.bak T/XML.hs T/XML.hs.bak T/AST.agda T/AST.agda.bak T/Parser.agda T/Parser.agda.bak T/IOLib.agda T/IOLib.agda.bak T/Main.agda T/Main.agda.bak T/T.dtd T/T.dtd.bak T/Test T/Lex.hs T/Par.hs T/Par.info T/ParData.hs Makefile
	-rmdir -p T/

# EOF
