-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language kx.

module Kx.Abs where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Typ = TVar Ident | TArr Typ Typ | TAll Ident Typ
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Exp
    = EVar Ident
    | EFLam Ident Typ Exp
    | EFApp Exp Exp
    | ETLam Ident Exp
    | ETApp Exp Typ
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

