-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Kx.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Kx.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Kx.Abs.Ident -> Result
transIdent x = case x of
  Kx.Abs.Ident string -> failure x

transTyp :: Kx.Abs.Typ -> Result
transTyp x = case x of
  Kx.Abs.TVar ident -> failure x
  Kx.Abs.TArr typ1 typ2 -> failure x
  Kx.Abs.TAll ident typ -> failure x

transExp :: Kx.Abs.Exp -> Result
transExp x = case x of
  Kx.Abs.EVar ident -> failure x
  Kx.Abs.EFLam ident typ exp -> failure x
  Kx.Abs.EFApp exp1 exp2 -> failure x
  Kx.Abs.ETLam ident exp -> failure x
  Kx.Abs.ETApp exp typ -> failure x
