-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language T.

module T.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Typ = TNat | TFun Typ Typ
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Exp
    = EVar Ident
    | ENat Integer
    | ENatZ
    | ENatS Exp
    | ERec Exp Exp Exp Ident Exp
    | ELam Ident Typ Exp
    | EApl Exp Exp
    | ELet Ident Exp Exp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

