-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module T.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified T.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: T.Abs.Ident -> Result
transIdent x = case x of
  T.Abs.Ident string -> failure x

transTyp :: T.Abs.Typ -> Result
transTyp x = case x of
  T.Abs.TNat -> failure x
  T.Abs.TFun typ1 typ2 -> failure x

transExp :: T.Abs.Exp -> Result
transExp x = case x of
  T.Abs.EVar ident -> failure x
  T.Abs.ENat integer -> failure x
  T.Abs.ENatZ -> failure x
  T.Abs.ENatS exp -> failure x
  T.Abs.ERec exp1 exp2 exp3 ident exp4 -> failure x
  T.Abs.ELam ident typ exp -> failure x
  T.Abs.EApl exp1 exp2 -> failure x
  T.Abs.ELet ident exp1 exp2 -> failure x
